-- Drop existing table if it exists
DROP TABLE IF EXISTS responses;

-- Create new responses table for readiness assessment (20 scenarios)
CREATE TABLE responses (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  q1          INTEGER NOT NULL CHECK (q1 BETWEEN 1 AND 5),
  q2          INTEGER NOT NULL CHECK (q2 BETWEEN 1 AND 5),
  q3          INTEGER NOT NULL CHECK (q3 BETWEEN 1 AND 5),
  q4          INTEGER NOT NULL CHECK (q4 BETWEEN 1 AND 5),
  q5          INTEGER NOT NULL CHECK (q5 BETWEEN 1 AND 5),
  q6          INTEGER NOT NULL CHECK (q6 BETWEEN 1 AND 5),
  q7          INTEGER NOT NULL CHECK (q7 BETWEEN 1 AND 5),
  q8          INTEGER NOT NULL CHECK (q8 BETWEEN 1 AND 5),
  q9          INTEGER NOT NULL CHECK (q9 BETWEEN 1 AND 5),
  q10         INTEGER NOT NULL CHECK (q10 BETWEEN 1 AND 5),
  q11         INTEGER NOT NULL CHECK (q11 BETWEEN 1 AND 5),
  q12         INTEGER NOT NULL CHECK (q12 BETWEEN 1 AND 5),
  q13         INTEGER NOT NULL CHECK (q13 BETWEEN 1 AND 5),
  q14         INTEGER NOT NULL CHECK (q14 BETWEEN 1 AND 5),
  q15         INTEGER NOT NULL CHECK (q15 BETWEEN 1 AND 5),
  q16         INTEGER NOT NULL CHECK (q16 BETWEEN 1 AND 5),
  q17         INTEGER NOT NULL CHECK (q17 BETWEEN 1 AND 5),
  q18         INTEGER NOT NULL CHECK (q18 BETWEEN 1 AND 5),
  q19         INTEGER NOT NULL CHECK (q19 BETWEEN 1 AND 5),
  q20         INTEGER NOT NULL CHECK (q20 BETWEEN 1 AND 5),
  total_score INTEGER NOT NULL,
  score_pct   REAL NOT NULL,
  readiness_level TEXT NOT NULL,
  submitted_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
